export const USER_AUTHENTICATED = 'USER_AUTHENTICATED';
export const GET_USER = 'GET_USER'
export const GET_USER_AVATAR = 'GET_USER_AVATAR'
export const GET_USER_COLLECTION = 'GET_USER_COLLECTION'
export const GET_LOGIN_TYPE = 'GET_LOGIN_TYPE'
export const USER_RENDER = 'USER_RENDER'
